import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Roboto } from 'next/font/google';
import '@/app/ui/globals.css';
import MainHeader from '@/components/main-header/main-header';
import MainSidebar from '@/components/main-sidebar/main-sidebar';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Whitehall',
  description: 'Generated by create romr',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <div className='grid grid-cols-main-grid'>
          <MainHeader />
          <MainSidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
